// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test, Vm} from "forge-std/Test.sol";
import {Groth16Verifier} from "../../src/zk/Groth16Verifier.sol";
import {SolvencyVerifier} from "../../src/zk/SolvencyVerifier.sol";

/// @notice Tests the on-chain Groth16 verifier against a *real* proof
///         generated by snarkjs from circuits/HealthFactorThreshold.circom —
///         not a hand-rolled mock. Regenerating this fixture:
///
///           cd circuits
///           node build/HealthFactorThreshold_js/generate_witness.js \
///             build/HealthFactorThreshold_js/HealthFactorThreshold.wasm \
///             build/input_valid.json build/witness_valid.wtns
///           npx snarkjs groth16 prove build/HealthFactorThreshold_final.zkey \
///             build/witness_valid.wtns build/proof_valid.json build/public_valid.json
///           npx snarkjs generatecall build/public_valid.json build/proof_valid.json
///
///         The witness corresponds to: collateralValueRay = 30,000e18,
///         debtValueRay = 20,000e18, liquidationThreshold = 0.85e18,
///         thresholdRay = 1e18 (proving HF >= 1). Actual HF here is
///         30,000 * 0.85 / 20,000 = 1.275, so the underlying claim is true
///         and the circuit's constraints are satisfiable — this is what
///         "Verifier contract accepts a valid health-factor proof" means in
///         the PRD's success metric.
contract SolvencyVerifierTest is Test {
    Groth16Verifier internal groth16;
    SolvencyVerifier internal solvency;

    // ── Real proof + public signals from build/proof_valid.json / public_valid.json ──
    // (built explicitly per-test via _validProof() below — Solidity state-array
    // initializers don't play nicely with these very long hex literals)

    function setUp() public {
        groth16 = new Groth16Verifier();
        solvency = new SolvencyVerifier(address(groth16));
    }

    function _validProof()
        internal
        pure
        returns (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c,
            uint256 commitment,
            uint256 liquidationThreshold,
            uint256 thresholdRay
        )
    {
        a = [
            0x03ce5583633db573f8a9838d392929598383e96ebfa85668e82b4599f05b37e8,
            0x01cf2f4604e4bfe6f618806f21cf53b9b478d2838b00fa32b294600201f870c4
        ];
        b = [
            [
                0x0d063e311dac4b7a0c41460abb5da906cf9aa4a6d5fb921dcf2199449514bf62,
                0x1b4cefef88dc1a6ea4e250ed7adb636491cff83f15cba72d7d30e68bef815d16
            ],
            [
                0x2d41004545159bc244f410bd86de035cb9ecfa41cee2a95b59264167f1d5cc51,
                0x0f66af7381fd0591a5a3b46b9799222dcb577dda6f5b026ef1458bc71e7bc5d3
            ]
        ];
        c = [
            0x24676c48e8a36fedd770f0142c2a8e2d8858e877c4e2fbbbc1fe0c233a835f5d,
            0x2bfbf2610ca0a46db5c4eed97c5b3fd79af5991a6a78716ef3fc3a085a0ea71b
        ];
        commitment = 0x11554017a7a7787e39d4dd04e5b8633c551867009283facedf0516b47ea7c9ed;
        liquidationThreshold = 850_000_000_000_000_000; // 0.85e18
        thresholdRay = 1_000_000_000_000_000_000; // 1e18 — proving HF >= 1
    }

    // ================================================================
    // Accepts a valid proof
    // ================================================================

    function test_Groth16Verifier_AcceptsRealValidProof() public view {
        (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c,
            uint256 commitment,
            uint256 liquidationThreshold,
            uint256 thresholdRay
        ) = _validProof();

        uint256[3] memory pubSignals = [commitment, liquidationThreshold, thresholdRay];
        assertTrue(groth16.verifyProof(a, b, c, pubSignals));
    }

    function test_SolvencyVerifier_CheckSolvency_AcceptsValidProof() public view {
        (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c,
            uint256 commitment,
            uint256 liquidationThreshold,
            uint256 thresholdRay
        ) = _validProof();

        assertTrue(solvency.checkSolvency(a, b, c, commitment, liquidationThreshold, thresholdRay));
    }

    function test_SolvencyVerifier_VerifySolvency_EmitsOnValidProof() public {
        (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c,
            uint256 commitment,
            uint256 liquidationThreshold,
            uint256 thresholdRay
        ) = _validProof();

        vm.expectEmit(true, true, false, true, address(solvency));
        emit SolvencyVerifier.SolvencyProven(address(this), commitment, liquidationThreshold, thresholdRay);

        bool valid = solvency.verifySolvency(a, b, c, commitment, liquidationThreshold, thresholdRay);
        assertTrue(valid);
    }

    // ================================================================
    // Rejects an invalid proof
    // ================================================================
    // A Groth16 proof is only valid for the exact public signals it was
    // generated against. Reusing the same proof bytes against ANY tampered
    // public signal — wrong commitment, wrong threshold, wrong LT — must be
    // rejected. This is exactly the property that makes the proof meaningful:
    // if it verified regardless of public inputs, it would prove nothing.

    function test_Groth16Verifier_RejectsProof_WithWrongCommitment() public view {
        (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c,,
            uint256 liquidationThreshold,
            uint256 thresholdRay
        ) = _validProof();

        uint256 wrongCommitment = 0xdead;
        uint256[3] memory pubSignals = [wrongCommitment, liquidationThreshold, thresholdRay];

        assertFalse(groth16.verifyProof(a, b, c, pubSignals));
    }

    function test_Groth16Verifier_RejectsProof_WithHigherClaimedThreshold() public view {
        // Same proof, same commitment/LT, but claiming a higher minimum HF
        // than what was actually proven (e.g. HF >= 2 instead of HF >= 1).
        // The real position's HF (1.275) does satisfy >= 1 but not >= 2 —
        // and regardless, this is a *different* proof obligation than the
        // one the proof bytes were generated for, so it must reject.
        (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c,
            uint256 commitment,
            uint256 liquidationThreshold,
        ) = _validProof();

        uint256 higherThreshold = 2_000_000_000_000_000_000; // 2e18
        uint256[3] memory pubSignals = [commitment, liquidationThreshold, higherThreshold];

        assertFalse(groth16.verifyProof(a, b, c, pubSignals));
    }

    function test_Groth16Verifier_RejectsProof_WithWrongLiquidationThreshold() public view {
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256 commitment,, uint256 thresholdRay) =
            _validProof();

        uint256 wrongLt = 500_000_000_000_000_000; // 0.5e18 instead of 0.85e18
        uint256[3] memory pubSignals = [commitment, wrongLt, thresholdRay];

        assertFalse(groth16.verifyProof(a, b, c, pubSignals));
    }

    function test_Groth16Verifier_RejectsGarbageProof() public view {
        uint256[2] memory garbageA = [uint256(1), uint256(2)];
        uint256[2][2] memory garbageB = [[uint256(3), uint256(4)], [uint256(5), uint256(6)]];
        uint256[2] memory garbageC = [uint256(7), uint256(8)];
        uint256[3] memory pubSignals = [uint256(9), uint256(10), uint256(11)];

        assertFalse(groth16.verifyProof(garbageA, garbageB, garbageC, pubSignals));
    }

    function test_SolvencyVerifier_CheckSolvency_RejectsTamperedProof() public view {
        (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c,,
            uint256 liquidationThreshold,
            uint256 thresholdRay
        ) = _validProof();

        assertFalse(solvency.checkSolvency(a, b, c, 0xdead, liquidationThreshold, thresholdRay));
    }

    function test_SolvencyVerifier_VerifySolvency_DoesNotEmitOnInvalidProof() public {
        (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c,,
            uint256 liquidationThreshold,
            uint256 thresholdRay
        ) = _validProof();

        // recordLogs + assert no SolvencyProven log, rather than expectEmit
        // (which would fail the test if the event ISN'T emitted as expected —
        // here we want to confirm it correctly stays silent).
        vm.recordLogs();
        bool valid = solvency.verifySolvency(a, b, c, 0xdead, liquidationThreshold, thresholdRay);
        assertFalse(valid);

        Vm.Log[] memory logs = vm.getRecordedLogs();
        assertEq(logs.length, 0, "should not emit SolvencyProven for a rejected proof");
    }

    // ================================================================
    // Constructor
    // ================================================================

    function test_Constructor_RevertsOnZeroVerifier() public {
        vm.expectRevert("SolvencyVerifier: zero verifier");
        new SolvencyVerifier(address(0));
    }
}
