// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Groth16Verifier} from "./Groth16Verifier.sol";

/// @title SolvencyVerifier
/// @notice Verifies "health factor >= threshold" zero-knowledge proofs produced
///         by the HealthFactorThreshold circuit (see /circuits), without the
///         prover ever revealing their collateral or debt amounts on-chain.
///
///         This wraps the raw `Groth16Verifier.verifyProof` (generated by
///         `snarkjs zkey export solidityverifier`, unmodified) with named
///         parameters matching the circuit's actual public signals, plus an
///         event so a proof-of-solvency can be pointed to later (e.g. by a
///         frontend badge, or a higher-LTV-tier gate) without re-verifying.
///
///         Public signal order is fixed by the circuit's own
///         `component main {public [commitment, liquidationThreshold, thresholdRay]}`
///         declaration — see circuits/HealthFactorThreshold.circom.
///
///         Scope note: this contract answers "does a valid proof exist for
///         this commitment/threshold pair" — it does not itself check that
///         `commitment` corresponds to any real on-chain position. Binding
///         commitments to actual Pool positions (e.g. computed and stored at
///         `borrow()` time) is the natural next step for using this as a
///         gate inside the protocol itself; see circuits/README.md.
contract SolvencyVerifier {
    Groth16Verifier public immutable verifier;

    event SolvencyProven(
        address indexed prover,
        uint256 indexed commitment,
        uint256 liquidationThreshold,
        uint256 thresholdRay
    );

    constructor(address _verifier) {
        require(_verifier != address(0), "SolvencyVerifier: zero verifier");
        verifier = Groth16Verifier(_verifier);
    }

    /// @notice Verifies a health-factor-threshold proof and, if valid, emits
    ///         a record of the claim (commitment + threshold proven against —
    ///         never the underlying collateral/debt values, which the
    ///         verifier never sees in the first place).
    /// @param pA, pB, pC   Groth16 proof points, as produced by `snarkjs generatecall`.
    /// @param commitment   Poseidon(collateralValueRay, debtValueRay, salt) — the
    ///                     value the prover committed to off-chain.
    /// @param liquidationThreshold RAY-scaled liquidation threshold used in the proof.
    /// @param thresholdRay  RAY-scaled minimum health factor being proven (e.g. 1e18 for HF >= 1).
    /// @return valid  True if the proof verifies against the given public signals.
    function verifySolvency(
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        uint256 commitment,
        uint256 liquidationThreshold,
        uint256 thresholdRay
    ) external returns (bool valid) {
        uint256[3] memory pubSignals = [commitment, liquidationThreshold, thresholdRay];

        valid = verifier.verifyProof(pA, pB, pC, pubSignals);

        if (valid) {
            emit SolvencyProven(msg.sender, commitment, liquidationThreshold, thresholdRay);
        }
    }

    /// @notice Same check as `verifySolvency` but without emitting — useful
    ///         for a frontend/keeper that just wants a yes/no answer.
    function checkSolvency(
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        uint256 commitment,
        uint256 liquidationThreshold,
        uint256 thresholdRay
    ) external view returns (bool valid) {
        uint256[3] memory pubSignals = [commitment, liquidationThreshold, thresholdRay];
        return verifier.verifyProof(pA, pB, pC, pubSignals);
    }
}
